server:
  port: 8084
spring:
  datasource:
    druid:
      url: jdbc:mysql://101.42.149.76:49153/gulimall_pms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=False&serverTimezone=GMT%2B8
      username: root
      password: machaojin
      driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  mapper-locations: classpath:mybatis/machaojin/*.xml
  type-aliases-package: com.machaojin.domain