server:
  port: 8084
spring:
  profiles:
    active: dev
    #    active: prod
    #    active: test
  datasource:
    druid:
      url: jdbc:mysql://101.42.149.76:49153/gulimall_pms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=False&serverTimezone=GMT%2B8
      username: root
      password: machaojin
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false #关闭缓存
  redis:
    host: 101.42.149.76
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000 #缓存过期时间
      key-prefix: PRODUCT_ #缓存前缀
      use-key-prefix: true
      cache-null-values: true #是否缓存空值，用于解决缓存穿透问题



#原mybatis
#mybatis:
#  mapper-locations: classpath:mybatis/machaojin/*.xml
#  type-aliases-package: com.machaojin.domain

#升级到MyBatis Plus
mybatis-plus:
  mapper-locations: classpath:mybatis/machaojin/*.xml
  type-aliases-package: com.machaojin.domain
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


