server:
  port: 8083
spring:
  profiles:
    active: dev
    #    active: prod
    #    active: test
  datasource:
    druid:
      url: jdbc:mysql://101.42.149.76:49153/gulimall_ums?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=False&serverTimezone=GMT%2B8
      username: root
      password: machaojin



mybatis-plus:
  mapper-locations: classpath:mybatis/machaojin/*.xml
  type-aliases-package: com.machaojin.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
