spring:
  profiles:
    active: dev
    #    active: prod
    #    active: test
  cloud:
   gateway:
     routes:
       #第三方工具类路由
       - id: third-party_route
         uri: lb://third-party
         predicates:
           - Path=/api/third-party/**
         filters:
           - RewritePath=/api/third-party/?(?<segment>.*), /third-party/$\{segment}

       #产品微服务路由
       - id: product_route
         uri: lb://product
         predicates:
           - Path=/api/product/**
               ##路径重写，将api路径重写成renren-fast/路径，后面的参数不变
         filters:
           - RewritePath=/api/product/?(?<segment>.*), /$\{segment}

      #会员服务路由
       - id: member_route
         uri: lb://member
         predicates:
           - Path=/api/member/**
          ##路径重写，将api路径重写成renren-fast/路径，后面的参数不变
         filters:
           - RewritePath=/api/member/?(?<segment>.*), /$\{segment}


       #仓库服务路由
       - id: ware_route
         uri: lb://ware
         predicates:
           - Path=/api/ware/**
           ##路径重写，将api路径重写成renren-fast/路径，后面的参数不变
         filters:
           - RewritePath=/api/ware/?(?<segment>.*), /$\{segment}

       #订单服务路由
       - id: order_route
         uri: lb://order
         predicates:
           - Path=/api/order/**
          ##路径重写，将api路径重写成renren-fast/路径，后面的参数不变
         filters:
           - RewritePath=/api/order/?(?<segment>.*), /$\{segment}


       #人人开源后台管理路由
       - id: admin_route
         uri: lb://renren-fast
         predicates:
           - Path=/api/**
          ##路径重写，将api路径重写成renren-fast/路径，后面的参数不变
         filters:
           - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}



##前端项目发送请求时带着api
  ## 503的是服务未找到，因为lb是进行负载均衡  引入 spring-cloud-starter-loadbalancer 依赖就好
 ## 503 的 gatefilter 格式不对- RewritePath=/api/?(?<segment>.*), /renren-fast\{segment}
##http://localhost:8087/api/captcha.jpg?uuid=7ef0bd09-7836-4578-85ab-b16a01379419  现在注册中心中找到renren-fast，但是地址时错的，需要重写