server:
  port: 8082
spring:
  datasource:
    druid:
      url: jdbc:mysql://101.42.149.76:49153/gulimall_sms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: machaojin



mybatis:
  mapper-locations: classpath:mybatis/machaojin/*.xml
  type-aliases-package: com.machaojin.domain
